# Production Environment Configuration
# GitHub Environment: production

name: production
description: Production environment for Clinical Trial Platform - Live system

# Environment Variables
variables:
  ENVIRONMENT: prod
  AWS_REGION: us-east-1
  NODE_ENV: production
  LOG_LEVEL: warn
  API_TIMEOUT: 10000
  MONITORING_LEVEL: comprehensive

# Strict approval rules for production
protection_rules:
  reviewers:
    - type: team
      name: clinical-trial-senior-team
    - type: user
      username: tech-lead
    - type: user
      username: product-owner
  prevent_self_review: true
  required_reviewers: 2
  deployment_timeout: 60  # 60 minutes for thorough review

# Production deployment rules - very restrictive
deployment_rules:
  # Only main branch can deploy to production
  deployment_branches:
    protected_branches: true
    custom_branch_policies: false
  
  # 10-minute wait timer for final review
  wait_timer: 10  # 10 minutes
  
  # Never auto-deploy to production
  auto_deployment: false

# Secrets required for production environment
required_secrets:
  - AWS_ACCESS_KEY_ID_PROD
  - AWS_SECRET_ACCESS_KEY_PROD
  - SNYK_TOKEN
  - LHCI_GITHUB_APP_TOKEN
  - PRODUCTION_DB_PASSWORD
  - JWT_SECRET
  - ENCRYPTION_KEY

# Production monitoring and alerting secrets
required_monitoring_secrets:
  - SLACK_WEBHOOK_URL
  - DATADOG_API_KEY
  - SENTRY_DSN
  - PAGERDUTY_INTEGRATION_KEY
  - AWS_CLOUDWATCH_LOG_GROUP

# Production environment configuration
configuration:
  # Production-grade resource scaling
  scaling:
    lambda_memory: 1024
    lambda_timeout: 30
    lambda_reserved_concurrency: 100
    aurora_min_capacity: 2
    aurora_max_capacity: 16
    aurora_backup_retention: 35
  
  # Comprehensive monitoring and alerting
  monitoring:
    enabled: true
    retention_days: 365
    detailed_monitoring: true
    custom_metrics: true
    alerting: true
    real_user_monitoring: true
    synthetic_monitoring: true
  
  # Maximum security settings
  security:
    enforce_https: true
    enable_waf: true
    enable_vpc_flow_logs: true
    backup_retention_days: 365
    encryption_at_rest: true
    encryption_in_transit: true
    key_rotation: true
    access_logging: comprehensive
    compliance_monitoring: true
  
  # Production cost optimization
  cost_optimization:
    auto_scaling: true
    spot_instances: false  # No spot instances in production
    lifecycle_policies: true
    reserved_capacity: true
    rightsizing_enabled: true

# Production feature flags - very conservative
feature_flags:
  debug_mode: false
  performance_testing: false
  experimental_features: false
  mock_external_services: false
  detailed_logging: false
  canary_deployments: true
  circuit_breakers: true

# Strict production quality gates
quality_gates:
  unit_test_coverage: 90  # Higher threshold for production
  security_scan: required
  performance_baseline: required
  accessibility_check: required
  end_to_end_tests: required
  load_testing: required
  security_penetration_test: required
  disaster_recovery_test: required

# Production data management
data_management:
  seed_data: false
  anonymized_data: false  # Real data in production
  backup_strategy: enterprise
  data_retention_days: 2555  # 7 years for healthcare compliance
  disaster_recovery: enabled
  point_in_time_recovery: enabled
  cross_region_backup: enabled

# Canary deployment configuration
canary_deployment:
  enabled: true
  initial_percentage: 5
  increment_percentage: 10
  increment_interval: 300  # 5 minutes
  health_check_grace_period: 600  # 10 minutes
  rollback_threshold: 1  # 1% error rate triggers rollback
  success_threshold: 99.9  # 99.9% success rate required

# Maintenance windows
maintenance_windows:
  preferred:
    - day: sunday
      start_time: "02:00"
      end_time: "04:00"
      timezone: "UTC"
    - day: wednesday
      start_time: "02:00"
      end_time: "04:00"
      timezone: "UTC"
  emergency_contact:
    - type: pagerduty
      escalation_policy: "clinical-trial-production"
    - type: slack
      channel: "#clinical-trial-alerts"

# High availability configuration
high_availability:
  multi_az: true
  auto_failover: true
  backup_strategy: continuous
  rpo_target: 60  # 1 minute recovery point objective
  rto_target: 300  # 5 minutes recovery time objective

# Performance requirements
performance_requirements:
  availability: 99.9
  response_time_p95: 500  # 500ms
  response_time_p99: 1000  # 1 second
  throughput_rps: 1000  # 1000 requests per second
  concurrent_users: 10000

# Security requirements
security_requirements:
  hipaa_compliance: required
  gdpr_compliance: required
  penetration_testing_frequency: quarterly
  vulnerability_scanning_frequency: weekly
  security_training_frequency: monthly
  incident_response_plan: required

# Compliance and auditing
compliance:
  audit_logging: comprehensive
  data_lineage: required
  change_management: required
  access_reviews: monthly
  compliance_reports: automated
  retention_policies: enforced

# Disaster recovery
disaster_recovery:
  backup_frequency: continuous
  backup_testing: monthly
  failover_testing: quarterly
  recovery_procedures: documented
  business_continuity_plan: updated

# Production monitoring thresholds
monitoring_thresholds:
  error_rate: 0.1  # 0.1%
  response_time_p95: 500  # 500ms
  cpu_utilization: 70  # 70%
  memory_utilization: 80  # 80%
  disk_utilization: 85  # 85%
  database_connections: 80  # 80% of max

# Alerting configuration
alerting:
  error_rate_threshold: 1  # 1%
  response_time_threshold: 1000  # 1 second
  availability_threshold: 99.5  # 99.5%
  escalation_intervals: [5, 15, 30]  # minutes
  notification_channels:
    - pagerduty
    - slack
    - email